// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/persons": {
    params: {};
  };
  "/cameras": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/verification": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/persons" | "/cameras" | "/logs" | "/verification";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/persons.tsx": {
    id: "routes/persons";
    page: "/persons";
  };
  "routes/cameras.tsx": {
    id: "routes/cameras";
    page: "/cameras";
  };
  "routes/logs.tsx": {
    id: "routes/logs";
    page: "/logs";
  };
  "routes/verification.tsx": {
    id: "routes/verification";
    page: "/verification";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/persons": typeof import("./app/routes/persons.tsx");
  "routes/cameras": typeof import("./app/routes/cameras.tsx");
  "routes/logs": typeof import("./app/routes/logs.tsx");
  "routes/verification": typeof import("./app/routes/verification.tsx");
};